### ISSUE TITLE
这个报错怎么解决啊

### ISSUE THREAD

**Issue by WC-wuqi** [ZororoZ/fscanOutput#3]
______                    ____        _               _   
|  ____|                  / __ \      | |             | |  
| |__ ___  ___ __ _ _ __ | |  | |_   _| |_ _ __  _   _| |_ 
|  __/ __|/ __/ _` | '_ \| |  | | | | | __| '_ \| | | | __|
| |  \__ \ (_| (_| | | | | |__| | |_| | |_| |_) | |_| | |_ 
|_|  |___/\___\__,_|_| |_|\____/ \__,_|\__| .__/ \__,_|\__|
                                          | |              
                                          |_|             
============================================================
                                         ---By zoro123 v1.03
           
Traceback (most recent call last):
  File "FscanOutput_v1.03.py", line 231, in <module>
    OpenPort(list1)
  File "FscanOutput_v1.03.py", line 44, in OpenPort
    port = u.replace(ip[0], '').strip(':')
IndexError: list index out of range

**Comment by ZororoZ** [comment]
根据提供的报错信息
   IndexError: list index out of range  （索引超出了列表的有效范围）  
疑似是生成的result.txt扫描文件中误添加多列数据造成的
