### ISSUE TITLE
读取报错

### ISSUE THREAD

**Issue by 1ighttack** [ZororoZ/fscanOutput#6]
Traceback (most recent call last):
  File "FscanOutput_v2.1_plus.py", line 339, in <module>
    OpenPort(list1)
  File "FscanOutput_v2.1_plus.py", line 100, in OpenPort
    OutPut('OpenPort', sheetList)
  File "FscanOutput_v2.1_plus.py", line 303, in OutPut
    for row in sheetName[f"A1:{chr(65 + len(list1[0]) - 1)}1"]:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/openpyxl/worksheet/worksheet.py", line 357, in __getitem__
    min_col, min_row, max_col, max_row = range_boundaries(key)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/openpyxl/utils/cell.py", line 135, in range_boundaries
    raise ValueError("{0} is not a valid coordinate or range")
ValueError: {0} is not a valid coordinate or range

**Comment by ZororoZ** [comment]
txt文件中端口行误添加列操作导致
